# Generated by Django 5.1.6 on 2025-02-26 19:41

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('disabled_at', models.DateField(default=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Now(), '+', models.Value(datetime.timedelta(days=7))))),
                ('inviter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
